mysql:
  host: '192.168.1.249'
  user: 'test'
  password: 'test'
  database: 'test'
  port: 3306

mongodb:
  host: '192.168.1.181'
  port: 27017
  database: test

test:
  machine:
    - 192.168.1.132
    - 192.168.1.133
    - 192.168.1.134
  services:
    xxx-service1:
      port: 31235
    xxx-service2:
      port: 31238
